In [ ]:
import pandas as pd
import sqlite3

DATABASE_NAME = 'odds.db'

conn = sqlite3.connect(DATABASE_NAME)
table_name = 'player_props'
df = pd.read_sql(f'''SELECT * FROM {table_name}''', conn)

,event_id,event_name,sport_key,market_type,outcome_type,player_name,point_value,odds,event_commence_time,updated_dttm
0,e10fe83ee6178a598e7fa84ea0913366,Philadelphia Eagles @ New York Giants,americanfootball_nfl,player_anytime_td,Yes,Saquon Barkley,NaN,-160.0,2025-10-09 20:15:00 EDT,2025-10-09 13:20:06 EDT
1,e10fe83ee6178a598e7fa84ea0913366,Philadelphia Eagles @ New York Giants,americanfootball_nfl,player_anytime_td,Yes,Jalen Hurts,NaN,-135.0,2025-10-09 20:15:00 EDT,2025-10-09 13:20:06 EDT
2,e10fe83ee6178a598e7fa84ea0913366,Philadelphia Eagles @ New York Giants,americanfootball_nfl,player_anytime_td,Yes,Cam Skattebo,NaN,145.0,2025-10-09 20:15:00 EDT,2025-10-09 13:20:06 EDT
3,e10fe83ee6178a598e7fa84ea0913366,Philadelphia Eagles @ New York Giants,americanfootball_nfl,player_anytime_td,Yes,AJ Brown,NaN,185.0,2025-10-09 20:15:00 EDT,2025-10-09 13:20:06 EDT
4,e10fe83ee6178a598e7fa84ea0913366,Philadelphia Eagles @ New York Giants,americanfootball_nfl,player_anytime_td,Yes,DeVonta Smith,NaN,250.0,2025-10-09 20:15:00 EDT,2025-10-09 13:20:06 EDT

In [5]:
df[(df['player_name'] == 'Jalen Hurts') & (df['market_type'] == 'player_pass_yds')]

,event_id,event_name,sport_key,market_type,outcome_type,player_name,point_value,odds,event_commence_time,updated_dttm
50,e10fe83ee6178a598e7fa84ea0913366,Philadelphia Eagles @ New York Giants,americanfootball_nfl,player_pass_yds,Over,Jalen Hurts,199.5,-115.0,2025-10-09 20:15:00 EDT,2025-10-09 13:20:06 EDT
51,e10fe83ee6178a598e7fa84ea0913366,Philadelphia Eagles @ New York Giants,americanfootball_nfl,player_pass_yds,Under,Jalen Hurts,199.5,-115.0,2025-10-09 20:15:00 EDT,2025-10-09 13:20:06 EDT