In [1]:
import pandas as pd
import sqlite3

DATABASE_NAME = 'odds.db'

conn = sqlite3.connect(DATABASE_NAME)
table_name = 'player_props'
df = pd.read_sql(f"""SELECT * FROM {table_name} WHERE market_type = 'player_pass_yds' ORDER BY event_commence_time DESC""", conn)
df.head()

,event_id,event_name,sport_key,market_type,outcome_type,player_name,point_value,odds,event_commence_time,updated_dttm
0,438868ff90501a1fe9a0fbecbee9dc12,Philadelphia Eagles @ Green Bay Packers,americanfootball_nfl,player_pass_yds,Over,Jalen Hurts,190.5,-115.0,2025-11-10 20:15:00 EST,2025-11-06 11:42:58 EST
1,438868ff90501a1fe9a0fbecbee9dc12,Philadelphia Eagles @ Green Bay Packers,americanfootball_nfl,player_pass_yds,Under,Jalen Hurts,190.5,-118.0,2025-11-10 20:15:00 EST,2025-11-06 11:42:58 EST
2,438868ff90501a1fe9a0fbecbee9dc12,Philadelphia Eagles @ Green Bay Packers,americanfootball_nfl,player_pass_yds,Over,Jordan Love,229.5,-115.0,2025-11-10 20:15:00 EST,2025-11-06 11:42:58 EST
3,438868ff90501a1fe9a0fbecbee9dc12,Philadelphia Eagles @ Green Bay Packers,americanfootball_nfl,player_pass_yds,Under,Jordan Love,229.5,-115.0,2025-11-10 20:15:00 EST,2025-11-06 11:42:58 EST
4,349d53a4f89591312ea528e81b786474,Pittsburgh Steelers @ Los Angeles Chargers,americanfootball_nfl,player_pass_yds,Over,Justin Herbert,259.5,-115.0,2025-11-09 20:20:00 EST,2025-11-06 11:42:05 EST

In [2]:
import pandas as pd
import sqlite3

DATABASE_NAME = 'odds.db'

conn = sqlite3.connect(DATABASE_NAME)
table_name = 'player_props'
df = pd.read_sql(f"""SELECT DISTINCT market_type FROM {table_name}""", conn)
df

                  market_type
0           player_anytime_td
1       player_kicking_points
2        player_pass_attempts
3     player_pass_completions
4   player_pass_interceptions
5             player_pass_tds
6             player_pass_yds
7        player_reception_yds
8           player_receptions
9        player_rush_attempts
10            player_rush_yds

In [2]:
df[(df['player_name'].str.contains('goff', case=False)) & (df['market_type'] == 'player_pass_yds')]

,event_id,event_name,sport_key,market_type,outcome_type,player_name,point_value,odds,event_commence_time,updated_dttm
10,93365f943b3aa23705bc9e1c7b47d7f8,Detroit Lions @ Washington Commanders,americanfootball_nfl,player_pass_yds,Over,Jared Goff,255.5,-115.0,2025-11-09 16:25:00 EST,2025-11-06 11:42:00 EST
11,93365f943b3aa23705bc9e1c7b47d7f8,Detroit Lions @ Washington Commanders,americanfootball_nfl,player_pass_yds,Under,Jared Goff,255.5,-115.0,2025-11-09 16:25:00 EST,2025-11-06 11:42:00 EST
90,cf95657d78ab3e515203df1d19c3b0c2,Minnesota Vikings @ Detroit Lions,americanfootball_nfl,player_pass_yds,Over,Jared Goff,240.5,-115.0,2025-11-02 13:00:00 EST,2025-10-31 12:05:48 EDT
91,cf95657d78ab3e515203df1d19c3b0c2,Minnesota Vikings @ Detroit Lions,americanfootball_nfl,player_pass_yds,Under,Jared Goff,240.5,-115.0,2025-11-02 13:00:00 EST,2025-10-31 12:05:48 EDT
158,b808059d3ccc754ace4a3d23b58e47e8,Tampa Bay Buccaneers @ Detroit Lions,americanfootball_nfl,player_pass_yds,Over,Jared Goff,267.5,-115.0,2025-10-20 19:00:00 EDT,2025-10-20 12:48:26 EDT
159,b808059d3ccc754ace4a3d23b58e47e8,Tampa Bay Buccaneers @ Detroit Lions,americanfootball_nfl,player_pass_yds,Under,Jared Goff,267.5,-115.0,2025-10-20 19:00:00 EDT,2025-10-20 12:48:26 EDT
170,82e432d5d8bc0b5a6cbe0c324de90de3,Detroit Lions @ Kansas City Chiefs,americanfootball_nfl,player_pass_yds,Over,Jared Goff,235.5,-115.0,2025-10-12 20:20:00 EDT,2025-10-09 13:42:15 EDT
171,82e432d5d8bc0b5a6cbe0c324de90de3,Detroit Lions @ Kansas City Chiefs,americanfootball_nfl,player_pass_yds,Under,Jared Goff,235.5,-115.0,2025-10-12 20:20:00 EDT,2025-10-09 13:42:15 EDT